app:
  HostName: ""
  Port: 6000
  ConnectionTimeToLiveSec: 60
log:
  Level: "DEBUG"
kafka:
  Brokers:
    - "localhost:29092"
  SchemaRegistryUrl: http://localhost:8081
  OutputTopicName: "sensor_data"
