app:
  HostName: "localhost:9092"
  Port: 6000
  ConnectionTimeToLiveSec: 60
log:
  Level: "DEBUG"
kafka:
  Brokers:
    - "localhost1:9092"
    - "localhost2:9092"
  OutputTopicName: "egts_package_sample"
