version: '3.7'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    networks:
    - zookeeper
    healthcheck:
      test: ruok | nc localhost:2181 = imok
    ports:
    - "2181:2181"
    container_name: dev-zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
    - zookeeper
    - kafka
    ports:
    - "9092:9092"
    - "9093:9093"
    container_name: dev-kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
    - zookeeper
    - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    networks:
    - zookeeper
    - kafka
    - apps
    ports:
    - "8081:8081"
    container_name: dev-schema-registry

  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    depends_on:
    - zookeeper
    - kafka
    - schema-registry
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://rest-proxy:8082
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    networks:
    - zookeeper
    - kafka
    - apps
    ports:
    - "8082:8082"
    container_name: dev-rest-proxy

  landoop-ui:
    image: landoop/kafka-topics-ui
    depends_on:
    - zookeeper
    - kafka
    - schema-registry
    - rest-proxy
    environment:
      PROXY: "true"
      KAFKA_REST_PROXY_URL: http://rest-proxy:8082
    ports:
    - "8000:8000"
    networks:
    - apps
    container_name: dev-landoop

networks:
  zookeeper:
  kafka:
  apps:
