// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     egtsmessage.avsc
 */

package avro

type NavigationSystem int32

const (
	NavigationSystemUknown  NavigationSystem = 0
	NavigationSystemGLONASS NavigationSystem = 1
	NavigationSystemGPS     NavigationSystem = 2
	NavigationSystemGalileo NavigationSystem = 3
	NavigationSystemCompass NavigationSystem = 4
	NavigationSystemBeidou  NavigationSystem = 5
	NavigationSystemDORIS   NavigationSystem = 6
)

func (e NavigationSystem) String() string {
	switch e {
	case NavigationSystemUknown:
		return "Uknown"
	case NavigationSystemGLONASS:
		return "GLONASS"
	case NavigationSystemGPS:
		return "GPS"
	case NavigationSystemGalileo:
		return "Galileo"
	case NavigationSystemCompass:
		return "Compass"
	case NavigationSystemBeidou:
		return "Beidou"
	case NavigationSystemDORIS:
		return "DORIS"

	}
	return "unknown"
}
